### ISSUE TITLE
Can you guys create an inventory source plugin?

### ISSUE THREAD

**Issue by k-kingsley** [phoenixnap/ansible-collection-pnap#24]
I would be extremely useful to have an ansible inventory source plugin that i could use to dynamically generate an inventory. This functions much like the [server_info.py](https://github.com/phoenixnap/ansible-collection-pnap/blob/master/plugins/modules/server_info.py) module except it is explicitly used outside of the playbook as an inventory.

For your reference there are a bunch of examples: https://docs.ansible.com/ansible/latest/collections/index_inventory.html

**Comment by pajuga** [comment]
support for inventory plugin added in version 1.17.0.
